window.FREE_NAVY_CONFIG = {
  netlifyIdentityEnabled: true,
  portalApiPath: "/api/portal",
  inviteMemberPath: "/api/invite-member",
  signupLinkPath: "/api/signup-link",
  membershipRequestPath: "/api/membership-request",
  gameDataSyncPath: "/api/sync-game-data",
  backupPath: "/api/backups",
  warehouseImagePath: "/api/warehouse-image",
  organisationName: "Free Navy",
  livePatch: "4.8.3",
  liveEnvironment: "LIVE",
  allowSamplePreviewWhenUnconfigured: true,
  uexProxyPath: "/api/uex",
  liveVersionPath: "/api/live-version",
  officialStarCitizenUrl: "https://robertsspaceindustries.com/",
  pageBackgrounds: {
    public: "/assets/backgrounds/public-home.svg",
    dashboard: "/assets/backgrounds/dashboard-command.svg",
    search: "/assets/backgrounds/search-databank.svg",
    notifications: "/assets/backgrounds/notifications-comms.svg",
    watchlist: "/assets/backgrounds/watchlist.svg",
    verification: "/assets/backgrounds/live-verification.svg",
    warehouse: "/assets/backgrounds/warehouse-cargo.svg",
    workorders: "/assets/backgrounds/work-orders.svg",
    crafting: "/assets/backgrounds/crafting-fabrication.svg",
    refinery: "/assets/backgrounds/refinery-command.svg",
    trade: "/assets/backgrounds/trade-routes.svg",
    knowledge: "/assets/backgrounds/where-to-buy.svg",
    catalog: "/assets/backgrounds/catalog-databank.svg",
    mining: "/assets/backgrounds/mining-operations.svg",
    salvaging: "/assets/backgrounds/salvage-operations.svg",
    auctions: "/assets/backgrounds/auction-vault.svg",
    market: "/assets/backgrounds/member-market.svg",
    contracts: "/assets/backgrounds/contracts-board.svg",
    treasury: "/assets/backgrounds/treasury-ledger.svg",
    operations: "/assets/backgrounds/operations-briefing.svg",
    crew: "/assets/backgrounds/crew-finder.svg",
    fleet: "/assets/backgrounds/fleet-hangar.svg",
    rescue: "/assets/backgrounds/medical-rescue.svg",
    exploration: "/assets/backgrounds/exploration-nav.svg",
    intel: "/assets/backgrounds/intelligence-recon.svg",
    incidents: "/assets/backgrounds/incident-review.svg",
    training: "/assets/backgrounds/training-academy.svg",
    kits: "/assets/backgrounds/equipment-kits.svg",
    wikelo: "/assets/backgrounds/wikelo-rewards.svg",
    members: "/assets/backgrounds/members-roster.svg",
    orgchart: "/assets/backgrounds/org-chart.svg",
    knowledgebase: "/assets/backgrounds/knowledge-base.svg",
    sync: "/assets/backgrounds/sync-control.svg",
    admin: "/assets/backgrounds/admin-control.svg",
    backup: "/assets/backgrounds/json-backup.svg"
  },
  backgroundPosition: { public: "center", default: "center" }
};
